'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowLeft, Bath, CalendarDays, ChevronRight, Edit3, LineChart, Plus, Scissors, Scale, X } from 'lucide-react'
import { pets } from '@/lib/mock-data'

const detail = {
  orange: { weight: 5.2, records: [['2026/09/12','5.2 kg'],['2026/08/20','5.3 kg'],['2026/07/18','5.2 kg']], internal: ['2026/08/15','每3个月','还有2个月'], external: ['2026/08/20','每1个月','该驱虫了'] },
  cola: { weight: 11.3, records: [['2026/09/14','11.3 kg'],['2026/08/22','11.4 kg'],['2026/07/20','11.1 kg']], internal: ['2026/08/15','每3个月','还有2个月'], external: ['2026/08/20','每1个月','还有12天'] },
} as const

export function PetDetailScreen({ id }: { id: string }) {
  const pet = pets.find((item) => item.id === id) ?? pets[0]
  const info = detail[pet.id as keyof typeof detail] ?? detail.orange
  const [sheet, setSheet] = useState<'weight' | 'deworm' | 'grooming' | null>(null)
  const [saved, setSaved] = useState(false)
  const isDog = pet.type === '狗'

  return <main className="min-h-dvh bg-background pb-10">
    <div className="mx-auto max-w-3xl px-4 pb-12 pt-5 md:px-8 md:pt-8">
      <header className="mb-6 flex items-center justify-between"><Link href="/" className="flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft className="size-4" />返回</Link><button className="flex items-center gap-1.5 text-sm text-muted-foreground"><Edit3 className="size-4" />编辑</button></header>
      <section className="overflow-hidden rounded-[28px] bg-card shadow-[0_20px_45px_-30px_rgba(80,60,40,.45)]">
        <div className="relative h-64 md:h-80"><img src={pet.photo} alt={`${pet.name}的照片`} className="h-full w-full object-cover" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-foreground/55 to-transparent p-6 pt-20 text-card"><p className="text-xs tracking-wide text-card/75">{pet.breed} · {pet.type === '猫' ? 'Female' : 'Male'}</p><h1 className="mt-1 text-3xl font-medium">{pet.name}</h1><p className="mt-1 text-sm text-card/80">{pet.age}</p></div></div>
      </section>
      <section className="mt-6 rounded-[24px] bg-card p-5 ring-1 ring-border/60"><div className="flex items-start justify-between"><div><p className="text-xs text-muted-foreground">Weight</p><p className="mt-2 font-mono text-4xl font-semibold">{info.weight} <span className="text-base font-sans font-normal text-muted-foreground">kg</span></p><p className="mt-1 text-xs text-muted-foreground">3天前记录 · 较上次 -0.1kg</p></div><LineChart className="size-5 text-sage-foreground" /></div><div className="mt-5 h-12 overflow-hidden rounded-2xl bg-sage/10 px-2"><svg viewBox="0 0 300 48" className="h-full w-full" preserveAspectRatio="none"><path d="M0 30 C35 25 45 34 75 23 S120 28 150 17 S195 28 225 13 S270 20 300 8" fill="none" stroke="currentColor" strokeWidth="2" className="text-sage-foreground" /></svg></div><div className="mt-5 divide-y divide-border">{info.records.map(([date,value]) => <div key={date} className="flex justify-between py-2.5 text-sm"><span className="text-muted-foreground">{date}</span><span className="font-mono text-foreground">{value}</span></div>)}</div><div className="mt-4 flex gap-3"><button onClick={() => setSheet('weight')} className="flex items-center gap-1.5 text-sm font-medium text-sage-foreground"><Plus className="size-4" />记录体重</button><button className="ml-auto text-sm text-muted-foreground">查看全部</button></div></section>
      <section className="mt-5 rounded-[24px] bg-card p-5 ring-1 ring-border/60"><div className="flex items-center justify-between"><div><p className="text-xs text-muted-foreground">Deworming</p><h2 className="mt-1 text-lg font-medium">驱虫记录与计划</h2></div><button onClick={() => setSheet('deworm')} className="flex items-center gap-1 text-sm text-muted-foreground"><Plus className="size-4" />记录</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{[['内驱',...info.internal],['外驱',...info.external]].map(([label,last,plan,status]) => <div key={label} className="rounded-2xl bg-background/60 p-4"><div className="flex justify-between"><span className="font-medium">{label}</span><span className={status === '该驱虫了' ? 'text-urgent' : 'text-safe'}>{status}</span></div><p className="mt-3 text-xs text-muted-foreground">最近：{last}</p><p className="mt-1 text-xs text-muted-foreground">计划：{plan}</p></div>)}</div><div className="mt-4 flex gap-4 text-sm text-muted-foreground"><button>计划设置</button><button>查看记录</button></div></section>
      {isDog && <section className="mt-5 rounded-[24px] bg-card p-5 ring-1 ring-border/60"><div className="flex items-center justify-between"><div><p className="text-xs text-muted-foreground">Dog care</p><h2 className="mt-1 text-lg font-medium">洗澡 / 美容</h2></div><button onClick={() => setSheet('grooming')} className="flex items-center gap-1 text-sm text-muted-foreground"><Plus className="size-4" />记录</button></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-slate-blue/10 p-4"><Bath className="size-4 text-slate-blue-foreground" /><p className="mt-3 text-sm">洗澡 · 18天前</p></div><div className="rounded-2xl bg-apricot/10 p-4"><Scissors className="size-4 text-apricot-foreground" /><p className="mt-3 text-sm">美容 · 35天前</p></div></div></section>}
    </div>
    {sheet && <div className="fixed inset-0 z-50 flex items-end justify-center bg-foreground/20 p-3 md:items-center"><div className="w-full max-w-md rounded-[28px] bg-card p-5 shadow-2xl"><div className="flex justify-between"><h2 className="text-lg font-medium">{sheet === 'weight' ? '记录体重' : sheet === 'deworm' ? '记录驱虫' : '记录护理'}</h2><button onClick={() => setSheet(null)} aria-label="关闭"><X className="size-5" /></button></div><div className="mt-5 grid gap-3"><label className="text-sm text-muted-foreground">日期<input type="date" defaultValue="2026-09-15" className="mt-1 w-full rounded-xl bg-background p-3 text-foreground" /></label>{sheet === 'weight' && <label className="text-sm text-muted-foreground">体重 kg<input type="number" step="0.1" defaultValue={info.weight} className="mt-1 w-full rounded-xl bg-background p-3 text-foreground" /></label>}{sheet === 'deworm' && <><label className="text-sm text-muted-foreground">类型<select className="mt-1 w-full rounded-xl bg-background p-3 text-foreground"><option>内驱</option><option>外驱</option></select></label><label className="text-sm text-muted-foreground">品牌<input placeholder="可选" className="mt-1 w-full rounded-xl bg-background p-3 text-foreground" /></label></>}{sheet === 'grooming' && <label className="text-sm text-muted-foreground">项目<select multiple className="mt-1 w-full rounded-xl bg-background p-3 text-foreground"><option>洗澡</option><option>美容</option></select></label>}<button onClick={() => { setSaved(true); setSheet(null) }} className="mt-2 rounded-full bg-primary py-3 text-sm font-medium text-primary-foreground">保存记录</button></div></div></div>}
    {saved && <button onClick={() => setSaved(false)} className="fixed bottom-5 left-1/2 z-40 -translate-x-1/2 rounded-full bg-foreground px-4 py-2 text-sm text-background">已保存记录</button>}
  </main>
}
